[boris]
  version = 1

[build.dist-*]
  git = "refs/heads/master"

[build.branches-*]
  git = "refs/heads/topic/*"

[build.cabal-test-7-10]
  git = "refs/heads/master"

[build.cabal-test-branches-7-10]
  git = "refs/heads/topic/*"

[build.submodules]
  git = "refs/heads/master"

[build.submodules-branches]
  git = "refs/heads/topic/*"

[build.validate]
  git = "refs/heads/master"
