[master]
  version = 1
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20160623072912-ccea728/master-haskell-20160623072912-ccea728"
  sha1 = "e150d58a710c500eb908db492b3dcd0e532b2725"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  MAFIA_HAPPY = "true"
  BENCH = "true"
  PUBLISH_BENCH = "bmx.hs"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  MAFIA_HAPPY = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"

[build.cabal-test-dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  MAFIA_HAPPY = "true"
  CABAL_TEST = "true"

[build.cabal-test-branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  MAFIA_HAPPY = "true"
  CABAL_TEST = "true"
